name: Red Hat JBoss Data Virtualization
abbreviated_name: JBoss Data Virtualization
product_logo: data-virtualization.png
current_version: 6.3.0
product_category: application-development
documentation_minor_version: 6.3
xpaas_url: https://www.openshift.com/developers/jboss-data-virtualization
intro_video: https://vimeo.com/91533636
vimeo_album: http://vimeo.com/album/2982437
youtube_album: https://www.youtube.com/playlist?list=PLf3vm0UK6HKo6SigOgnSWYc6rhLemrDDS
skip_installation_instructions: true
skip_maven_instructions: true
index:
  desc: |
    A tool that brings operational and analytical insight from data dispersed in various business units, apps, and technologies.
buzz_tags:
  - datavirt
  - jboss datavirt
customer_portal_download_url: https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=data.services.platform&downloadType=distributions
guides:
  Release_Notes:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/release-notes/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/release-notes/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Release_Notes-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Release_Notes-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Release_Notes-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Release_Notes-en-US.epub
  Getting_Started_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/getting-started-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/getting-started-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Getting_Started_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Getting_Started_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Getting_Started_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Getting_Started_Guide-en-US.epub
  Quick_Starts_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/quick-starts-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/quick-starts-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Quick_Starts_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Quick_Starts_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Quick_Starts_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Quick_Starts_Guide-en-US.epub
  Using_the_Dashboard_Builder:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/using-the-dashboard-builder/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/using-the-dashboard-builder/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Using_the_Dashboard_Builder-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Using_the_Dashboard_Builder-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Using_the_Dashboard_Builder-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Using_the_Dashboard_Builder-en-US.epub
  Installation_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/installation-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/installation-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Installation_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Installation_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Installation_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Installation_Guide-en-US.epub
  Glossary_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/glossary-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/glossary-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Glossary_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Glossary_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Glossary_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Glossary_Guide-en-US.epub
  Administration_and_Configuration_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/administration-and-configuration-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/administration-and-configuration-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Administration_and_Configuration_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Administration_and_Configuration_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Administration_and_Configuration_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Administration_and_Configuration_Guide-en-US.epub
  Security_Guide:
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/security-guide/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/security-guide/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Security_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Security_Guide-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Security_Guide-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Security_Guide-en-US.epub
  Development_Guide_Volume_1_Client_Development:
    name: "Development Guide Volume 1: Client Development"
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/development-guide-volume-1-client-development/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/development-guide-volume-1-client-development/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_1_Client_Development-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_1_Client_Development-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_1_Client_Development-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_1_Client_Development-en-US.epub
  Development_Guide_Volume_2_Governance:
    name: "Development Guide Volume 2: Governance"
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/development-guide-volume-2-governance/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/development-guide-volume-2-governance/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_2_Governance-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_2_Governance-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_2_Governance-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_2_Governance-en-US.epub
  Development_Guide_Volume_3_Reference_Material:
    name: "Development Guide Volume 3: Reference Material"
    formats:
      html:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/paged/development-guide-volume-3-reference-material/
      html-single:
        url: https://access.redhat.com/documentation/en/red-hat-jboss-data-virtualization/6.3/single/development-guide-volume-3-reference-material/
      pdf:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_3_Reference_Material-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_3_Reference_Material-en-US.pdf
      epub:
        url: https://access.redhat.com/webassets/avalon/d/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_3_Reference_Material-en-US/Red_Hat_JBoss_Data_Virtualization-6.3-Development_Guide_Volume_3_Reference_Material-en-US.epub
description: 'An integration platform that unifies data from disparate sources into a single source and exposes the data as a reusable service.'
default_download_artifact_type: installer
downloads:
upstream_projects:
  - teiid
  - teiiddesigner
  - modeshape
featured_items:
  - image_url: http://design.jboss.org/jbossdeveloper/sitedesign/jbossdeveloper_1_0/makerfiles/images/developermaterials_datavirtualization.png
    url: /video/vimeo/76457404
    text: Launch into the virtual data world
evaluation: https://access.redhat.com/products/red-hat-jboss-data-virtualization/evaluation
