#
# This environment provides all testing resources. It is common across all concrete environment and as such this should be
# considered as a mixin environment definition. It is combined with the concrete environment definition
# at runtime to ensure that test resources only need to be defined once
#
version: '2'
services:
  unit_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL
      - RHD_DRIVER

  acceptance_tests:
    build: ../../awestruct
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    links:
      - selhub:hub
    environment:
      - ghprbActualCommit
      - github_status_api_token
      - PARALLEL_TEST
      - CUCUMBER_TAGS
      - SELENIUM_HOST=http://hub:4444/wd/hub
      - RHD_JS_DRIVER
      - RHD_DOCKER_DRIVER
      - BUILD_URL

  selhub:
    image: selenium/hub
    restart: always
    expose:
      - "4444"
    ports:
      - "4444"
    privileged: true
    environment:
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000

  docker_chrome:
    image: selenium/node-chrome
    volumes:
    - /dev/shm:/dev/shm
    links:
     - selhub:hub
    environment:
     - HUB_PORT_4444_TCP_ADDR=selhub
     - DBUS_SESSION_BUS_ADDRESS=/dev/null